"""Tests for autopypath._validate module."""

from pathlib import Path
from types import MappingProxyType


import pytest

from testspec import TestSpec, PytestAction, Assert

from autopypath.load_strategy import LoadStrategy
from autopypath.marker_type import MarkerType
from autopypath.path_resolution import PathResolution
from autopypath import _validate

# fmt: off

@pytest.mark.parametrize(
    'testspec', [
        PytestAction('MARKER_001',
            name='valid repo_markers',
            action=_validate.repo_markers,
            args=[{'.git': MarkerType.DIR, 'pyproject.toml': MarkerType.FILE}],
            expected={'.git': MarkerType.DIR, 'pyproject.toml': MarkerType.FILE}),
        PytestAction('MARKER_002',
            name='empty repo_markers',
            action=_validate.repo_markers, args=[{}],
            expected=None),
        PytestAction('MARKER_003',
            name='single repo_marker',
            action=_validate.repo_markers, args=[{'setup.py': MarkerType.FILE}],
            expected={'setup.py': MarkerType.FILE}),
        PytestAction('MARKER_004',
            name='string repo_markers',
            action=_validate.repo_markers, args=[{'.git': 'dir', 'setup.py': 'file'}],
            expected={'.git': MarkerType.DIR, 'setup.py': MarkerType.FILE}),
        PytestAction('MARKER_005',
            name='mixed type repo_markers',
            action=_validate.repo_markers, args=[{'.git': MarkerType.DIR, 'setup.py': 'file'}],
            expected={'.git': MarkerType.DIR, 'setup.py': MarkerType.FILE}),
        PytestAction('MARKER_006',
            name='invalid repo_marker',
            action=_validate.repo_markers, args=[{'.git': 'DIR'}],
            exception=ValueError),
        PytestAction('MARKER_007',
            name='invalid repo_marker type',
            action=_validate.repo_markers, args=[{'.git': 123}],
            exception=TypeError),
        PytestAction('MARKER_008',
            name='None repo_markers',
            action=_validate.repo_markers, args=[None],
            expected=None),
        PytestAction('MARKER_009',
            name='no repo_markers',
            action=_validate.repo_markers, kwargs={'value': {}},
            expected=None),
        PytestAction('MARKER_010',
            name='whitespace repo_marker key',
            action=_validate.repo_markers, args=[{'   ': MarkerType.DIR}],
            exception=ValueError),
        PytestAction('MARKER_011',
            name='non-string repo_marker key',
            action=_validate.repo_markers, args=[{123: MarkerType.DIR}],
            exception=TypeError),
        PytestAction('MARKER_012',
            name='non-mapping repo_markers',
            action=_validate.repo_markers, args=[[('setup.py', MarkerType.FILE)]],
            exception=TypeError),
        PytestAction('MARKER_013',
            name='repo_marker key exceeding max length',
            action=_validate.repo_markers, args=[{'a' * 65: MarkerType.DIR}],
            exception=ValueError),
        PytestAction('MARKER_014',
            name='repo_marker key containing path separator',
            action=_validate.repo_markers, args=[{'inva/lid': MarkerType.DIR}],
            exception=ValueError),
        PytestAction('MARKER_015',
            name='repo_marker key being Windows reserved name',
            action=_validate.repo_markers, args=[{'CON': MarkerType.FILE}],
            exception=ValueError),
        PytestAction('MARKER_016',
            name='repo_marker key containing forbidden characters',
            action=_validate.repo_markers, args=[{'inva<lid': MarkerType.FILE}],
            exception=ValueError),
        PytestAction('MARKER_017',
            name='repo_marker key being empty string',
            action=_validate.repo_markers, args=[{'': MarkerType.FILE}],
            exception=ValueError),
        PytestAction('MARKER_018',
            name='repo_marker key having leading whitespace',
            action=_validate.repo_markers, args=[{'  setup.py': MarkerType.FILE}],
            exception=ValueError),
        PytestAction('MARKER_019',
            name='repo_marker key having trailing whitespace',
            action=_validate.repo_markers, args=[{'setup.py  ': MarkerType.FILE}],
            exception=ValueError),
        PytestAction('MARKER_020',
            name='repo_marker key containing null character',
            action=_validate.repo_markers, args=[{'setup\0.py': MarkerType.FILE}],
            exception=ValueError),
        PytestAction('MARKER_021',
            name='Validate repo_marker attr returns MappingProxyType',
            action=_validate.repo_markers, args=[{'setup.py': MarkerType.FILE}],
            expected=MappingProxyType,
            assertion=Assert.ISINSTANCE),
    ]
)
def test_repo_markers(testspec: TestSpec) -> None:
    """Test Config with repo_markers."""
    testspec.run()

@pytest.mark.parametrize('testspec', [
    PytestAction('PATHS_001',
        name='valid list of paths',
        action=_validate.paths, args=[['src', 'lib', 'utils']],
        expected=(Path('src'), Path('lib'), Path('utils'))),
    PytestAction('PATHS_002',
        name='empty paths',
        action=_validate.paths, args=[[]],
        expected=None),
    PytestAction('PATHS_003',
        name='single path',
        action=_validate.paths, args=[['src']],
        expected=(Path('src'),)),
    PytestAction('PATHS_004',
        name='None paths',
        action=_validate.paths, kwargs={'value': None},
        expected=None),
    PytestAction('PATHS_005',
        name='no paths',
        action=_validate.paths, kwargs={'value': []},
        expected=None),
    PytestAction('PATHS_006',
        name='invalid path type',
        action=_validate.paths, args=[['src', 123, 'utils']],
        exception=TypeError),
    PytestAction('PATHS_007',
        name='Path objects',
        action=_validate.paths, args=[[Path('src'), Path('lib')]],
        expected=(Path('src'), Path('lib'))),
    PytestAction('PATHS_008',
        name='path having leading whitespace',
        action=_validate.paths, args=[['  src', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_009',
        name='path having trailing whitespace',
        action=_validate.paths, args=[['src  ', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_010',
        name='path being only whitespace',
        action=_validate.paths, args=[['   ', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_011',
        name='path being only forward slashes',
        action=_validate.paths, args=[['///', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_012',
        name='path being only backslashes',
        action=_validate.paths, args=[['\\\\\\', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_013',
        name='path having segment with leading whitespace',
        action=_validate.paths, args=[['src/  utils', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_014',
        name='path having segment with trailing whitespace',
        action=_validate.paths, args=[['src/utils  ', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_015',
        name='path having whitespace segment',
        action=_validate.paths, args=[['src/ /utils', 'lib']],
        exception=ValueError),
    PytestAction('PATHS_016',
        name='Path having segment being only whitespace',
        action=_validate.paths, args=[[Path('src/   /utils'), Path('lib')]],
        exception=ValueError),
    PytestAction('PATHS_017',
        name='Path having segment with leading whitespace',
        action=_validate.paths, args=[[Path('src/  utils'), Path('lib')]],
        exception=ValueError),
    PytestAction('PATHS_018',
        name='Path having segment with trailing whitespace',
        action=_validate.paths, args=[[Path('src/utils  /more'), Path('lib')]],
        exception=ValueError),
    PytestAction('PATHS_019',
        name='Create config with path being empty string',
        action=_validate.paths, args=[['']],
        exception=ValueError),
    PytestAction('PATHS_020',
        name='Create config with path being neither str nor Path',
        action=_validate.paths, args=[[123]],
        exception=TypeError),
    PytestAction('PATHS_021',
        name='Create config with paths being neither sequence nor None',
        action=_validate.paths, args=[123],
        exception=TypeError),
    PytestAction('PATHS_022',
        name='Validate paths attr returns tuple of Path objects',
        action=_validate.paths, args=[['src', 'lib']],
        expected=tuple,
        assertion=Assert.ISINSTANCE),
])
def test_paths(testspec: TestSpec) -> None:
    """Test Config with paths"""
    testspec.run()


@pytest.mark.parametrize('testspec', [
    PytestAction('LOAD_STRATEGY_001',
        name='valid load_strategy',
        action=_validate.load_strategy,
        args=[LoadStrategy.MERGE],
        expected=LoadStrategy.MERGE),
    PytestAction('LOAD_STRATEGY_002',
        name='load_strategy as string',
        action=_validate.load_strategy,
        args=['merge'],
        expected=LoadStrategy.MERGE),
    PytestAction('LOAD_STRATEGY_003',
        name='invalid load_strategy string',
        action=_validate.load_strategy,
        args=['invalid_strategy'],
        exception=ValueError),
    PytestAction('LOAD_STRATEGY_004',
        name='invalid load_strategy type',
        action=_validate.load_strategy,
        args=[123],
        exception=TypeError),
    PytestAction('LOAD_STRATEGY_005',
        name='None load_strategy',
        action=_validate.load_strategy,
        args=[None],
        expected=None),
])
def test_load_strategy(testspec: TestSpec) -> None:
    """Test Config with load_strategy"""
    testspec.run()

@pytest.mark.parametrize('testspec', [
    PytestAction('RESOLVE_001',
        name='valid path_resolution_order',
        action=_validate.path_resolution_order,
        args=[['manual', 'pyproject', 'dotenv']],
        expected=(PathResolution.MANUAL, PathResolution.PYPROJECT, PathResolution.DOTENV)),
    PytestAction('RESOLVE_002',
        name='path_resolution_order as enums',
        action=_validate.path_resolution_order,
        args=[[PathResolution.DOTENV, PathResolution.MANUAL]],
        expected=(PathResolution.DOTENV, PathResolution.MANUAL)),
    PytestAction('RESOLVE_003',
        name='invalid path_resolution_order string',
        action=_validate.path_resolution_order,
        args=[['invalid_source']],
        exception=ValueError),
    PytestAction('RESOLVE_004',
        name='invalid path_resolution_order type',
        action=_validate.path_resolution_order,
        args=[[123]],
        exception=TypeError),
    PytestAction('RESOLVE_005',
        name='empty path_resolution_order',
        action=_validate.path_resolution_order,
        args=[[]],
        expected=None),
    PytestAction('RESOLVE_006',
        name='None path_resolution_order',
        action=_validate.path_resolution_order,
        args=[None],
        expected=None),
    PytestAction('RESOLVE_007',
        name='no path_resolution_order',
        action=_validate.path_resolution_order,
        kwargs={'value': []},
        expected=None),
    PytestAction('RESOLVE_008',
        name='duplicate path_resolution_order entries',
        action=_validate.path_resolution_order,
        args=[['manual', 'pyproject', 'manual']],
        exception=ValueError),
    PytestAction('RESOLVE_009',
        name='single path_resolution_order entry',
        action=_validate.path_resolution_order,
        args=[['dotenv']],
        expected=(PathResolution.DOTENV,)),
    PytestAction('RESOLVE_010',
        name='mixed type path_resolution_order entries',
        action=_validate.path_resolution_order,
        args=[['manual', PathResolution.DOTENV, 'pyproject']],
        expected=(PathResolution.MANUAL, PathResolution.DOTENV, PathResolution.PYPROJECT)),
    PytestAction('RESOLVE_011',
        name='path_resolution_order having leading/trailing whitespace',
        action=_validate.path_resolution_order,
        args=[[' manual ', 'pyproject']],
        exception=ValueError),
    PytestAction('RESOLVE_012',
        name='path_resolution_order being neither sequence nor None',
        action=_validate.path_resolution_order,
        args=[123],
        exception=TypeError),
    PytestAction('RESOLVE_013',
        name='path_resolution_order containing non-str/non-enum',
        action=_validate.path_resolution_order,
        args=[['manual', 123]],
        exception=TypeError),
    PytestAction('RESOLVE_014',
        name="Create config with path_resolution_order as a string",
        action=_validate.path_resolution_order,
        args=['manual'],
        exception=TypeError),
])
def test_path_resolution_order(testspec: TestSpec) -> None:
    """Test Config with path_resolution_order"""
    testspec.run()
